apiVersion: apps/v1
kind: Deployment
metadata:
  name: pensiondetails-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pensiondetails
  template:
    metadata:
      labels:
        app: pensiondetails
    spec:
      containers:
      - name: pensiondetailsrepo
        image:  pensionmanagementcr.azurecr.io/pensiondetailsrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: processpensionsn

---
apiVersion: v1
kind: Service
metadata:
  name: pensiondetails
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: authorization
